[tox]
envlist = py311, tests, flake8, pylint, docs

[testenv]
package = wheel
deps =
    pytest
    pytest-cov
commands = pytest {posargs}

[testenv:tests]
package = wheel
deps =
    pytest
    pytest-cov
commands =
    pytest tests/ -v --tb=short {posargs}

[pytest]
testpaths = tests
addopts = --tb=short

[flake8]
max-line-length = 120
extend-ignore = E203, W503

[testenv:flake8]
deps = flake8
commands = flake8 src/diskripr tests

[testenv:pylint]
deps =
    pylint
    click
commands = pylint src/diskripr

[testenv:docs]
deps =
    sphinx
    sphinx-click
    myst-parser
    sphinx-rtd-theme
    click
commands =
    sphinx-build -W -n -b html docs docs/_build/html
